var GAME_LEVELS = [
  ["                                v                    v       v  v               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                        xxx       xxx           ",
   "                                                xxx                             ",
   "                      ooo              ooo                                  xx  ",
   "  xx          oo                                                             x  ",
   "  x                  xxxxx            xxxxx                                  x  ",
   "  x                                                                      o   x  ",
   "  x                                        e                                 x  ",
   "  x  @                 p                                                     x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxx                 xxxxxxxxxx  ",
   "             x!!x             x   x               x                 x           ",
   "             xxxx             x!!!x               x!!!!!!!!!!!!!!!!!x           ",
   "                              x!!!x               x!!!!!!!!!!!!!!!!!x           ",
   "                              xxxxx               xxxxxxxxxxxxxxxxxxx           ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        v         v         v         v              xxx",
   "                                      x!!x                                                                     xxx",
   "                                      x!!xxxxxxxxxx                                                            xxx",
   "                                      xx!!!!!!!!!!xx                                            o              xxx",
   "                                       xxxxxxxxxx!!x                                                      o    xxx",
   "                                                xx!x                                  o                        xxx",
   "                                                 x!x                                                           xxx",
   "                                                 xvx                        o                     xxxxxxxxxxxxxxxx",
   "                                                                                                  xxxxxxxxxxxxxxxx",
   "                                                                                         xxxxx    xxxxxxxxxxxxxxxx",
   "                                                                  o                                               ",
   "                                               x        o                      xxxxx            x                 ",
   "                                               x                                                                  ",
   "                                               x                     xxxxx            x                           ",
   "                                               x                                                                  ",
   "               o  o  o                         xx    xx   xxxxx             x                                     ",
   "                                               x     x                                                            ",
   "                                               x     x                                                            ",
   "                                               x     x            x                                               ",
   "                  e                            x    xx                                                            ",
   "     @                                         x     x                                                            ",
   "    xxx      xxxxxxxxxxxx      xx o xx         x     x                                                            ",
   "    xxx      xxxxxxxxxxxx      xx   xx         x     x                                                            ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!!xx  o  xx!!!!!!!!xx    x!!!!!!!!!!                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!xx       xxxxxxxxxx     x!!!!!!!xx!                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!x    o                 xx!!!!!!xx !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!x             p       xx!!!!!!xx  !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  @                                                                                                           ",
   "xxxxx                       o                                                                                 ",
   "xxxxx                                                                                                         ",
   "xxxxx                                                                                                         ",
   "                    o                                                                                         ",
   "         o                   xxxxx  x             x                                                           ",
   "                                    x     o       x                                                           ",
   "         o            xxxxx         x = =         x                                                           ",
   "                                    x     o       x                                                           ",
   "         o     xxxxx                x             x                                                           ",
   "                                    x     o   = = x                                                           ",
   "       xxxxx                        x             x                                                           ",
   "                                    x     o       x                                                           ",
   "                                    x                                                                         ",
   "                                    x     o                                  o                                ",
   "                                    x                                                                         ",
   "                                    x                                 o                                       ",
   "                                    xxxxxxxxxxxxxxx                                                           ",
   "                                                         o                     xxxxx      o                   ",
   "                                                                                                              ",
   "                                                         o             xxxxx              o                   ",
   "                                                                                                              ",
   "                                                         o     xxxxx                      o                   ",
   "                                                                                                              ",
   "                                                       xxxxx                              o                   ",
   "                                                                                                              ",
   "                                                                                          o                   ",
   "                                                                                                              ",
   "                                                                                          o                   ",
   "                                                                                                              ",
   "                                                                                          o                   ",
   "                                                                                                              ",
   "                                                                                     xxxxxxxxxxx              ",
   "                                                                                     xxxxxxxxxxx              ",
   "                                                                                     xxxxxxxxxxx              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
